from enum import Enum


class logMode(Enum):
    IS_DEBUG_DATA = "txn"
    IS_DEBUG_ALL = "all"
    IS_DEBUG_ERROR = "error"

#griff tags
class Griff_St_SString(Enum):
    #griff search string to get initial index
    search_string_1 = "Processor Called"
    search_string_2 = "Calling packs api with parameter operatorName"

class Griff_En_SString(Enum):
    search_string_1 = "Request completed"

#packs tags
class Packs_St_SString(Enum):
    search_string_1 = "Entering activateSubscriber"
    
class Packs_En_SString(Enum):
    search_string_1 = "prism Charging status:ERROR"
    search_string_2 = "subscriber activation status:"

#prism tags
class Prism_St_SString(Enum):
    #griff search string to get initial index
    search_string = "-process handler params for task {} for subType:{}"

class Prism_En_SString(Enum):
    #griff search string to get initial index
    search_string = "-Tlog record added:{}"

class PrismTlogErrorTag(Enum):
    """
    Enum error tag
    """
    SUB_TYPE_CHECK = "STCK=3,"
    CHECK_BALANCE = "CBAL=,3"
    RESERVE = "RSRV=3,"
    CHARGING = "CHG=3,"
    REMOTE_ACT = "RMAC=3,"
    REMOTE_DCT = "RMD=3,"
    DECTIVATION = "DCT=3,"
    CALLBACK = "CBCK=3,"
    CDR = "CRM=3,"
    INFORM_CSS = "CSS=3,"
    REFUND = "RFD=3,"
    INFORM_OMF = "OMF=3,"
    GENERIC_TASK1 = "GT1=3,"
    GENERIC_TASK2 = "GT2=3,"
    GENERIC_TASK3 = "GT3=3,"
    GENERIC_TASK4 = "GT4=3,"

class PrismTlogRetryTag(Enum):
    """
    Enum retry tag
    """
    SUB_TYPE_CHECK = "STCK=0,"
    CHECK_BALANCE = "CBAL=0,"
    RESERVE = "RSRV=0,"
    CHARGING = "CHG=0,"
    REMOTE_ACT = "RMAC=0,"
    REMOTE_DCT = "RMD=0,"
    DECTIVATION = "DCT=0,"
    CALLBACK = "CBCK=0,"
    CDR = "CRM=0,"
    INFORM_CSS = "CSS=0,"
    REFUND = "RFD=0,"
    INFORM_OMF = "OMF=0,"
    GENERIC_TASK1 = "GT1=0,"
    GENERIC_TASK2 = "GT2=0,"
    GENERIC_TASK3 = "GT3=0,"
    GENERIC_TASK4 = "GT4=0,"
    
class PrismTlogLowBalTag(Enum):
    """
    Enum low bal tag
    """
    CHECK_BALANCE = "CBAL=4,"
    CHARGING = "CHG=4,"

class PrismTlogNHFTag(Enum):
    """
    Enum no handler found tag
    """
    NHF = "NHF:NO handler configured for request"

class PrismTlogAwaitPushTag(Enum):
    """
    Enum await push tag
    """
    SUB_TYPE_CHECK = "STCK=8,"
    CHECK_BALANCE = "CBAL=8,"
    RESERVE = "RSRV=8,"
    CHARGING = "CHG=8,"
    REMOTE_ACT = "RMAC=8,"
    REMOTE_DCT = "RMD=8,"
    DECTIVATION = "DCT=8,"
    CALLBACK = "CBCK=8,"
    CDR = "CRM=8,"
    INFORM_CSS = "CSS=8,"
    REFUND = "RFD=8,"
    INFORM_OMF = "OMF=8,"
    GENERIC_TASK1 = "GT1=8,"
    GENERIC_TASK2 = "GT2=8,"
    GENERIC_TASK3 = "GT3=8,"
    GENERIC_TASK4 = "GT4=8,"
    
class PrismTlogAwaitPushTimeOutTag(Enum):
    """
    Enum timeout tag
    """
    SUB_TYPE_CHECK = ",-#TIMEOUT"
    CHECK_BALANCE = ",-#TIMEOUT"
    RESERVE = ",-#TIMEOUT"
    CHARGING = ",-#TIMEOUT"
    REMOTE_ACT = ",-#TIMEOUT"
    REMOTE_DCT = ",-#TIMEOUT"
    DECTIVATION = ",-#TIMEOUT"
    CALLBACK = ",-#TIMEOUT"
    CDR = ",-#TIMEOUT"
    INFORM_CSS = ",-#TIMEOUT"
    REFUND = ",-#TIMEOUT"
    INFORM_OMF = ",-#TIMEOUT"
    GENERIC_TASK1 = ",-#TIMEOUT"
    GENERIC_TASK2 = ",-#TIMEOUT"
    GENERIC_TASK3 = ",-#TIMEOUT"
    GENERIC_TASK4 = ",-#TIMEOUT"
    
class PrismTlogHandlerExp(Enum):
    CHARGING = "CHG=30,"
<<<<<<< HEAD
    # CHG = "CHG=41,"
=======
    CHG = "CHG=41,"
>>>>>>> 4e4c54d0b75e9ceb5152b4838060d0dcd9be6909

class PrismTlogSmsTag(Enum):
    SMS_INVALID = "I"
    SMS_RETRY_EXCEEDED = "E"
    SMS_PENDING = "P"
    SMS_SUSPENDED = "S"
    SMS_QUEUED = "Q"
    
class PrismTasks(Enum):
    """
    Task type class
    """
    SUB_TYPE_CHECK = "S"
    CHECK_BALANCE = "Q"
    RESERVE = "RA"
    CHARGING = "B"
<<<<<<< HEAD
    # CHG = "B"
=======
    CHG = "B"
>>>>>>> 4e4c54d0b75e9ceb5152b4838060d0dcd9be6909
    REMOTE_ACT = "R"
    REMOTE_DCT = "H"
    DECTIVATION = "D"
    CALLBACK = "C"
    CDR = "L"
    INFORM_CSS = "M"
    REFUND = "W"
    INFORM_OMF = "IO"
    GENERIC_TASK1 = "G1"
    GENERIC_TASK2 = "G2"
    GENERIC_TASK3 = "G3"
<<<<<<< HEAD
    GENERIC_TASK4 = "G4"
    
#daius activity type
class DaiusActivityType(Enum):
    Holding = "0"
    PreCampaignPage = "1"
    AgeVerificationCheck = "2"
    UserClickedAgeVerificationNo = "3"
    UserClickedAgeVerificationYes = "4"
    SubscribeCheck = "5"
    UserClickedSubscribeCancel = "6"
    UserClickedSubscribeConfirm = "7"
    AuthenticationFailed = "8"
    AlreadySubscribed = "9"
    CurrentlyUnsubscribed = "10"
    DeviceDetectionHD = "11"
    ChargingProfileAPI = "12"
    ActivatePacksAPI = "13"
    DMVendorCallbackAPI = "14"
    NotAuthenticatedRedirect = "15"
    AuthenticationRetry = "16"
    IncompatibleDevice = "17"
    DeviceUnsupportedRedirect = "18"
    SubscribeFailedRedirect = "19"
    GRIFFPurchaseRedirect = "20"
    GRIFFPurchaseRedirectReturn = "21"
    UserClickedSubscribedContinue1 = "22"
    UnknownError = "23"
    UnknownErrorRedirect = "24"
    SuccessfulSubscription = "25"
    FailedSubscription = "26"
    CannotPurchase = "27"
    CannotPurchaseRedirect = "28"
    UnknownBillingError = "29"
    UnknownBillingErrorRedirect = "30"
    LowBalanceError = "31"
    LowBalanceErrorRedirect = "32"
    InvalidSessionID = "33"
    ReturnRedirectParameterMissing = "34"
    UserIDMatchOnReturnAPIFailed = "35"
    ClientLoadAgeVerificationCheck = "36"
    ClientLoadSubscribeCheck = "37"
    ClientLoadSubscribeConfirm = "38"
    AuthenticationFailedWhiteList = "39"
    AgeVerificationCheckCookie = "40"
    InvalidGriffSessionID = "41"
    BlacklistedUser = "42"
    SubscribeCheckCookie = "43"
    UnsupportedContentItem = "44"
    NoStoreContentSupported = "45"
    LandingPageLoad = "46"
    LandingPageCookie = "47"
    SubscribePageLoad = "48"
    SubscribePageCookie = "49"
    UserClickedSubscribedContinue2 = "50"
    ConsentGatewayInfoAPI = "51"
    UnknownConsentGatewayInfoError = "52"
    ConsentGatewayProcessAPI = "53"
    UnknownConsentGatewayProcessError = "54"
    ConsentGatewayRedirectReturn = "55"
    ConsentGatewayCallback = "56"
    InvalidSessionID_UserAgent = "57"
    InvalidSessionID_UserID = "58"
    InvalidSessionID_CampaignMedium = "59"
    AcceptedSubscription = "60"
    InvalidSessionID_CampaignSource = "61"
    InvalidSessionID_CampaignID = "62"
    UserClickedAgeVerificationYes_AlreadySubscribed = "63"
    UserClickedStoreHomeLinkOnConfirmation = "64"
    BlockedUser = "65"
    ProductCheck = "66"
    TransComplete = "67"
    GoogleRecaptcha = "68"
    LimitExceeded = "69"
    LimitExceeded_Daily = "70"
    LimitExceeded_Weekly = "71"
    LimitExceeded_Monthly = "72"
    LimitExceeded_Daily_Weekly = "73"
    LimitExceeded_Daily_Monthly = "74"
    LimitExceeded_Weekly_Monthly = "75"
    LimitExceeded_Daily_Weekly_Monthly = "76"
    LimitExceededErrorRedirect = "77"
    CappingReached = "78"
    CappingReached_Hourly = "79"
    CappingReached_Daily = "80"
    CappingReached_Hourly_Daily = "81"
    CappingReachedErrorRedirect = "82"
    SubscribePageLoad_OnWifi = "83"
    ConfirmUnsubscribe = "84"
    UnsubscribeSuccess = "85"
    UnsubscribeError = "86"
    DMChargingProfileAPI = "88"
    DeactivatePacksAPI = "89"
    UnknownStatusCheckError = "90"
    OperatorSelectionRedirect = "91"
    UIMRedirect = "92"
    UIM_GRIFF_Identify_INFO = "93"
    UIM_GRIFF_Identify_PROCESS = "94"
    UIM_GRIFF_SendOTP_INFO = "95"
    UIM_GRIFF_SendOTP_PROCESS = "96"
    UIM_GRIFF_VerifyOTP_INFO = "97"
    UIM_GRIFF_VerifyOTP_PROCESS = "98"
    DeactivationSuccess = "99"
    ActivationCallbackSuccess = "100"
    ConsentGatewayRedirect = "103"
    MSISDNPageLoad = "104"
    FailedOTPVerification = "105"
    ValidateOTPForSubscription = "106"
    FailedOTPSend = "107"
    RenewalCallback = "108"
    AppInstalled = "109"
    UserIdentified = "110"
    OTPExpired = "111"
    HitProcessConsent = "112"
    OTPHitForSubscription = "113"
    OTPHitForIdentification = "114"
    SendUpgradeCallback = "115"
    ReceivedUpgradeCallback = "116"
    ChargingFailed = "117"
    PINHitForSubscription = "118"
    StoreSubscribedSuccessRedirection = "119"
    StoreAlreadySubscribedRedirection = "120"
    StoreFailureRedirection = "121"
    InsufficentFundsError = "133"
    UserIdentifiedthroughData = "134"
    Successful_Activation_on_sameday = "200"
    UserClickedSubscribeConfirmEligibleForSubscription = "201"
    UserClickedSubscribeConfirmNOTEligibleForSubscription = "202"
    BotFormSubmit = "300"
    BotAnchorClick = "301"
    BotCheckboxInput = "302"
    BotButtonSubmit = "303"
    BotSubscription = "304"
    JSNotSupported = "305"
    BlockedCountry = "306"
    BlockedOS = "307"
    BlockedWifiUser = "308"
    BlockedRecurDay = "309"
    BlockedBaitClick = "310"
    BlockedAntiForgery = "311"
    BotDetectedExternalService = "312"
    ExternalAntifraudServiceResponse = "313"
    BotBlockedExternalService = "314"
    UserLimitExceeded = "315"
    BlockDMCallbackOnLowChargedAmount = "316"
    BlockDMCallbackOnDelayedChargingCallback = "317"
    BlockedCircle = "318"
    QualityCheckResponse = "319"
    QualityCheckFailed = "320"
    GriffError = "321"
    InternalError = "322"
    OtherErrors = "323"
    SubscribeTouched = "324"
    Insufficent_Funds_Error = "325"
    Blacklisted_User = "326"
    VMSIssueTokenAPIRequest = "401"
    VMSIssueTokenRequestSuccess = "402"
    VMSIssueTokenFailure = "403"
    InitiatePayoutApiHitReceived = "500"
    InitiatePayoutApiValidationFailure = "501"
    PayoutSuccessful = "502"
    PayoutFailure = "503"
    InitiatePayoutApiRedirection = "504"
    PayoutRedirectionReceived = "505"
    PayoutRedirectionValidationFailure = "506"
    ResumeSubscriptionApiHitReceived = "520"
    ResumeSubscriptionApiValidationFailure = "521"
    GoogleRecaptchaV2PageLoad = "701"
    GoogleRecaptchaV2SuccessfulVerification = "702"
    ThirdPartyUserChargingProfileRequestReceived = "800"
    ThirdPartyUserChargingProfileValidationFailure = "801"
    ThirdPartyUserChargingProfileSuccess = "802"
    ThirdPartyUserChargingProfileFailure = "803"
    ThirdPartyAuthenticateRequestReceived = "804"
    ThirdPartyAuthenticateRequestValidationFailure = "805"
    ThirdPartyAuthenticateRequestSuccess = "806"
    ThirdPartyAuthenticateRequestFailure = "807"
    ThirdPartySendOTPRequestReceived = "808"
    ThirdPartySendOTPRequestValidationFailure = "809"
    ThirdPartySendOTPRequestSuccess = "810"
    ThirdPartySendOTPRequestFailure = "811"
    ThirdPartyVerifyOTPRequestReceived = "812"
    ThirdPartyVerifyOTPRequestValidationFailure = "813"
    ThirdPartyVerifyOTPRequestSuccess = "814"
    ThirdPartyVerifyOTPRequestFailure = "815"
=======
    GENERIC_TASK4 = "G4"
>>>>>>> 4e4c54d0b75e9ceb5152b4838060d0dcd9be6909
